### ISSUE TITLE
Standardize names

### ISSUE THREAD

**Issue by laughedelic** [bio4j/modules#12]
@eparejatobes @pablopareja 

We should set some canonical names for Bio4j modules, because it's already quite confusing: `Uniref` vs. `UniRef`, `GO` vs. `GeneOntology`, etc.

What I currently have this:
- `NCBITaxonomy`
- `GITaxonomyIndex`
- `RefSeq`
- `GeneOntology`
- `EnzymeDB`
- `UniprotKB`
- `UniRef`
- `ProteinInteractions`
- `IsoformSequences`

**Comment by eparejatobes** [comment]
agreed. @rtobes @pablopareja ?

**Comment by pablopareja** [comment]
It looks fine to me, the only thing's that these three:
- UniRef
- ProteinInteractions
- IsoformSequences

are actually part of UniprotKB whilst being modules themselves from our perspective...

**Comment by laughedelic** [comment]
Well, as I understood, each of these three things should be splitted on SwissProt and TrEMBL parts + their unions, right? So it's 9 modules actually.

**Comment by laughedelic** [comment]
No, sorry, I meant
- Uniprot
- UniRef
- ProteinInteractions
