### ISSUE TITLE
Bio4j modules hierarchy

### ISSUE THREAD

**Issue by laughedelic** [bio4j/modules#14]
@eparejatobes @pablopareja 
Here is the current hierarchy of Bio4j modules after introducing statika bundles:
![bio4j modules](https://f.cloud.github.com/assets/766656/1803190/c759dfb2-6c14-11e3-895e-79f98de072be.png)

This is made after Bio4j [wiki page](https://github.com/bio4j/Bio4j/wiki/Bio4j-modules) on modules (tried to preserve colors).

I guess, that I didn't split something that could be splitted on more parts or may be did something else wrong. So let's fix it and improve.

btw, I did this diagram in LucidChart chrome app, if you know something better and probably with collaborative editing...

**Comment by eparejatobes** [comment]
OK I'll check this

**Comment by laughedelic** [comment]
See corresponding sources [here](https://github.com/ohnosequences/bio4j-scala/blob/master/docs/src/titandb/Importer.md).
Also I think, `API` part should be reviewed. Personally, I don't see any point to make it bundle: dependencies are controlled through `ImportedDataBundle` and then binding it with `API` through `ModuleBundle`. On the other hand, it could be represented as just traits with proper parts of the abstract model interface. Related thing here is the `DistributionBundle`, which should expose this API.

**Comment by laughedelic** [comment]
Any suggestions about `APIBundle`? If no, I'm doing simple traits.

**Comment by laughedelic** [comment]
@eparejatobes @pablopareja 
I'm trying to make this diagram nicer for the FOSDEM presentation. How do you think, which one of these two is more obvious? Or may be you can suggest something different.
**before:**

## ![bio4jmodules](https://f.cloud.github.com/assets/766656/2029079/aa0751d0-88dc-11e3-91cb-8b5a85247985.png)

**after:**
![bio4jmodules union_layout](https://f.cloud.github.com/assets/766656/2029078/a9f0d48c-88dc-11e3-8fe3-5d1b33fd8767.png)

**Comment by pablopareja** [comment]
Mmm I don't know.
Actually there a couple of things mixed up in here.
On the one hand there are let's call it **_mandatory dependencies_** - _such as Uniref or protein interactions on Uniprot_, that make impossible to import a module without previously importing the other one.
On the other hand there are dependencies such as that of Uniprot on Gene Ontology or RefSeq which are let's call them **_optional_** since you can still go on with the importing process, the thing is just that such relationships with those modules won't be created.

**Comment by eparejatobes** [comment]
As far as I understand, there should be **different** modules, like in this example:
- UniProt _with the minimal amount of deps_
- GeneOntology _with the minimal amount of deps_
- UniProt+GeneOntology _which includes any linking/integration between these two datasources_

**Comment by laughedelic** [comment]
@pablopareja 
It complicates things a bit... Then there should be separate modules for uniprot _with_ refseq, for example, and _without_ it. Right?
Or we can show here only mandatory deps and mention other ones to say how actually complex it should be and how flexible the underlying system is needed. Because we neither have time for drawing the full diagram, nor it is implemented (what is drawn is).

**Comment by laughedelic** [comment]
@eparejatobes I agree in general with what you're saying, but in particular, as far as I understand, module UniProt _depends_ on the module GeneOntology, so the first and the third things in your list are the same.

But anyway, what do you think about the diagrams? @pablopareja if something there is wrong, please, correct me. I was relying on the picture from [the wiki](https://github.com/bio4j/Bio4j/wiki/Bio4j-modules).

**Comment by pablopareja** [comment]
Mmm yeah sorry about the diagram but it's a bit obsolete already...
I don't know, I don't mind about how many statika-bundle-modules you want to create or how it's the diagram design, I just wanted to point out that in my opinion we should not mix "mandatory" with "optional" dependencies :wink:

**Comment by laughedelic** [comment]
yeah, nobody mixes them — we are talking about mandatory dependencies. but what's the right diagram then? I mean, I wanted to show it in my talk...

**Comment by laughedelic** [comment]
it's not about statika bundles, it's about bio4j modules, which you import.

**Comment by pablopareja** [comment]
OK so:

### _Optional_ dependencies
- Uniprot KB --> Gene Ontology
- Uniprot KB --> Enzyme DB
- Uniprot KB --> RefSeq 
- Uniprot KB --> NCBI taxonomy

### _Mandatory_ dependencies
- Interactions --> Uniprot KB
- Uniref --> Uniprot KB
- Isoforms (sequences) --> Uniprot KB
- GI index for taxonomy tree --> NCBI taxonomy

**Comment by laughedelic** [comment]
I am confused now. In the `ImportNCBITaxonomyTitan` there is a conditional part `associateTaxonomy`, which creates edges from taxon nodes to some organism nodes (from UniProt as I understand), which at this point don't even exist.
Then some magic happens in the UniProt import, that it check if it has those edges and sets taxon id in it's nodes.
- So is this what you mean by an "optional dependency"? 
- Are then Gene Ontology and Enzyme DB independent by themselves? 
- Is it true, that both Uniprot and Interactions can be split on SwissProt and TrEMBL parts with respective dependencies between them (as it is on the diagram)?

**Comment by laughedelic** [comment]
Does this picture reflect what you are saying?
![bio4jmodules opt_deps](https://f.cloud.github.com/assets/766656/2030652/1c939242-88f9-11e3-8065-c6aa2eaa1ecd.png)

I know that layout is ugly, but I'll fix it later

**Comment by pablopareja** [comment]
Did you know that there exist two _"parallel"_ taxonomy trees? (Uniprot's and NCBI's)

> So is this what you mean by an "optional dependency"?
1. The program won't crash
2. They make sense as independent things in abstract too

> Are then Gene Ontology and Enzyme DB independent by themselves

Yes

> Is it true, that both Uniprot and Interactions can be split on SwissProt and TrEMBL parts with 
> respective dependencies between them (as it is on the diagram)?

I guess so

**Comment by laughedelic** [comment]
> Did you know that there exist two "parallel" taxonomy trees? (Uniprot's and NCBI's)

I figured it out, when I saw this `associateTaxonomy` thing. But I don't like that it appears in NCBITaxonomy import, because it makes it dependent — you have to know in advance, if you are going to import additional UniProt then or not.. Is it possible to move this association process to UniProt import program completely?

**Comment by pablopareja** [comment]
Well it only makes it dependent when you pass "true" in that argument.
It's the other way round, you should only pass true there when you previously imported Uniprot so that the program creates relationships among NCBI taxonomic units and those defined in Uniprot taxonomy tree.

**Comment by laughedelic** [comment]
Hm.. So it can be seen as
- a separate module for `NCBITaxonomy` (only)
- a separate module for `UniProt` (only)
- a separate module for connecting them, which depends on the previous two

analogously for other "optional dependencies"...

**Comment by laughedelic** [comment]
Something like this
![bio4jmodules connectors](https://f.cloud.github.com/assets/766656/2031108/60353bc2-88fe-11e3-85a9-42f0acfda78d.png)

**Comment by laughedelic** [comment]
Or this way (the same topology, just another layout):
![bio4jmodules connectors_octo](https://f.cloud.github.com/assets/766656/2031225/f0fc3b1e-88ff-11e3-9407-7507de1f030f.png)

**Comment by eparejatobes** [comment]
I don't think it's going to fit in one slide however you draw it

**Comment by laughedelic** [comment]
@eparejatobes 
:disappointed: so you want me not to use it at all? I can do a simpler diagram or put some variant of it (like the one in the very beginning of this thread) and say that the real hierarchy is more complex.. but just omitting it and talking about "module dependencies" and the profit of using statika waving hands in the air is kind of unconvincing

**Comment by laughedelic** [comment]
we will need to open a new issue for discussing this. this is too long-living
