### ISSUE TITLE
stable bio4j-scala

### ISSUE THREAD

**Issue by evdokim** [bio4j/modules#21]
I'm close to release first version of metapasta, but I have several concers about bio4j:
- is content of `my.nonexisting.bucket` is fixed? it seams that this database works for me not, but what happens if object of this bucket will be changed? probably is better to add some versions there.
- does it work for other accounts? are all objects there public?
- is s3://snapshots.era7.com/ohnosequences/bio4j-scala-distribution_2.10/0.2.0-SNAPSHOT/jars/bio4j-scala-distribution_2.10-fat.jar stable?

**Comment by laughedelic** [comment]
- I managed to separate this small Taxonomy Bio4j (see #19). So now
- I created a bucket `bio4j.releases` and added versions for bio4j release (e.g. `indexed_taxonomy/v0.1.0`)
- I wrote a nice test which
  - builds the module
  - checks that it works trying to retrieve Gorilla gorilla gorilla taxon by tax id
  - uploads it to S3 (release)
  - downloads it from there (distribution)
  - checks Gorilla taxon again for what it downloaded
- see code [here](https://github.com/ohnosequences/bio4j-scala/tree/feature/incremental-import/bio4j-ncbi-taxonomy/src/main/scala)
- the fat artifact is published at `s3://releases.era7.com/ohnosequences/bio4j-ncbi-taxonomy_2.10/0.1.0/jars/bio4j-ncbi-taxonomy_2.10-fat.jar`

you can use it like 

``` scala
import ohnosequences.bio4j.bundles._

NCBITaxonomyApplicator.install(NCBITaxonomyDistribution)
```

I'm restructuring project, so don't use `bio4j-scala-distribution` — it will be removed

---
- don't know about different accounts so far
- not sure if it's automatically published public (in that uploading manager didn't find a way to set this)

**Comment by evdokim** [comment]
I don't understand how to get `NodeRetrieverTitan`. They are no longer export it?

**Comment by evdokim** [comment]
and what the difference between NCBITaxonomyRelease and NCBITaxonomyDistribution?

**Comment by laughedelic** [comment]
In this bio4j-scala terminology (until we change it to something more obvious), 
- `ReleaseBundle` is a bundle that builds (imports) particular combination of modules and uploads it to S3 — so it should be done only once and you don't need it anymore (until next release)
- `DistributionBundle` is a bundle that you apply when you want to **use** some released `ReleaseBundle` — so that's what you want

And this `NCBITaxonomyDistribution` has the `nodeRetriever: NodeRetrieverTitan` val.
