### ISSUE TITLE
statika integration - library level

### ISSUE THREAD

**Issue by eparejatobes** [bio4j/modules#3]
Look at how we could modularize bio4j into bundles at the code level

**Comment by laughedelic** [comment]
Here is the inner bundles structure:
![document_2013-12-23_11-15-26](https://f.cloud.github.com/assets/766656/1802930/d6fcb144-6c0d-11e3-99ef-b622843ed67f.png)

**Comment by evdokim** [comment]
@laughedelic I liked yours hexes!

**Comment by laughedelic** [comment]
cool

**Comment by laughedelic** [comment]
The bundles structure is reviewed according to #19, so the main change is that `ImportedData` bundle can depend on a _released_ `Distribution` bundle instead of `ImportedData` — so that it will use ready database as it's initial state adding more data to it.

**Comment by laughedelic** [comment]
no discussion, closing
