### ISSUE TITLE
sbt env setup instructions

### ISSUE THREAD

**Issue by eparejatobes** [bio4j/modules#7]
send link to @pablopareja and help him if needed -> @eparejatobes

**Comment by laughedelic** [comment]
Hi, @pablopareja! :wave: 
Here is our sbt-plugin, which contains a standard set of settings: [ohnosequences/nice-sbt-settings](https://github.com/ohnosequences/nice-sbt-settings).
SO for creating a new project, you can use [era7bio/scala-2.10.g8](https://github.com/era7bio/scala-2.10.g8) template:

``` bash
$ g8 era7bio/scala-2.10.g8

A basic scala 2.10 project

version [0.1.0-SNAPSHOT]:
name [default]: foo
org [era7]: ohnosequences

Template applied in ./foo
```

it will ask you a couple of questions and then you get a new empty project. There, main configuration file is `build.sbt` and as you see it's really simple:

``` scala
Nice.scalaProject

name := "foo"

description := "foo project"

organization := "ohnosequences"

bucketSuffix := "era7.com"
```

Then, I don't know, see [ohnosequences/nice-sbt-settings](https://github.com/ohnosequences/nice-sbt-settings) docs and ask me/us if you need any help. Sbt is easy and quite nice, once you get used to it. So until you are, you _will_ have questions — and I'll be glad to help you with anything.
