### ISSUE TITLE
titandb-specific project

### ISSUE THREAD

**Issue by eparejatobes** [bio4j/modules#8]

**Comment by eparejatobes** [comment]
@pablopareja the repo is already there: [bio4j/bio4j-titandb](https://github.com/bio4j/bio4j-titandb)

**Comment by eparejatobes** [comment]
@evdokim @pablopareja @laughedelic what we're doing there:
- [x] moving all titandb-specific code there
- [x] configuring dependencies (depend on the generic bio4j project)
- [x] generate a runnable fat jar

**Comment by eparejatobes** [comment]
@pablopareja need something?

**Comment by eparejatobes** [comment]
@pablopareja for getting an exec jar, you just need to add to your `build.sbt`:

``` scala
Nice.fatArtifactSettings

mainClass in assembly := Some("com.example.Main")
```

your jar will be called the same as that one for your library, but with `fat` appended somewhere (I don't know exactly where)

**Comment by laughedelic** [comment]
in the end: `...-fat.jar`

**Comment by eparejatobes** [comment]
see https://github.com/era7bio/docs/wiki/fat-jars

**Comment by eparejatobes** [comment]
the fat jar is already there, so closing
